version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/go-sql-driver/mysql
      - go get -u github.com/erikbryant/wow-database
      - go get -u github.com/erikbryant/web

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - go vet ./...

      # Run all tests included with our application
      - go test ./...

  build:
    commands:

      # Build our application
      - go build -o wow

artifacts:
  files:
    - wow
    - appspec.yml
    - buildspec.yml
    # - config/*
    # - codedeploy/*
    # - cloudformation/*
