#!/bin/zsh -eu

waitForInternet () {
  while true ; do
    ping -qc 1 google.com && return
    sleep 1
  done
}

vspace () {
  echo
  echo
  echo
  echo
  echo
  echo
  echo
  echo
  echo
  echo
  echo
  echo
}

waitForInternet

open -a Battle.net.app
open -a "Google Chrome"

vspace

cd ~/dev/wow
go run main/wow.go -passPhrase unlock -oauth=true

vspace

cd ~/dev/wowMerchant
make cache

vspace
