name: govulncheck

on: [push, pull_request]

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: 'true'
      - name: Check out source code
        uses: actions/checkout@v6
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
