name: go test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Golang
      uses: actions/setup-go@v6
      with:
        go-version: 'stable'
        check-latest: 'true'
    - name: Install sound libraries
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev
        sudo apt-get install libudev-dev
    - name: Check out source code
      uses: actions/checkout@v6
    - name: Test
      run: |
        go test ./...
